# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.25
# 

Name:       hello

# >> macros
# << macros

Summary:    Simple "Hello World"
Version:    1.0.0
Release:    1
Group:      Amusements/Games
License:    GPL
URL:        https://wiki.merproject.org/wiki/Building_against_Mer_in_Community_OBS
Source0:    %{name}-%{version}.tar.bz2
#Source100:  hello.yaml

%description
Sample package for Mer


%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post


%files
%defattr(-,root,root,-)
%{_bindir}/hello
# >> files
# << files
